import { Inter } from "next/font/google";
import Provider from "./context/AuthContext.jsx";
import ToastContext from "./context/ToastContainer.jsx";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <ToastContext />
          {children}
        </Provider>
      </body>
    </html>
  );
}
